#!/usr/bin/env bash

url=$1
title=$2
path=$3

escape_string()
{
   printf '%s' "$1" | tr -d '[!"#$%&'\''()+,./:;<=>?@[\]^_`{|}~]'
}

filepath=$(escape_string "$title")

date=`date +"%Y-%m-%dT%H:%M"`

mkdir -p $path
cat << EOF > "$path/$filepath.md"
# $title
$url
$date
EOF

cmd=(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --print-to-pdf="$path/$filepath.pdf" $url )
"${cmd[@]}"
