#!/usr/bin/env bash

url=$1
title=$2
path=$3

date=`date +"%Y-%m-%dT%H:%M"`

mkdir -p $path
cat << EOF > "$path/$title.md"
$url
$date
EOF

cmd=(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --disable-gpu --print-to-pdf="$path/$title.pdf" $url )
"${cmd[@]}"
