#!/usr/bin/env bash
set -e
set -u
set -o pipefail

export TB_CLI_TELEMETRY_OPTOUT=1

if [[ -n ${TB_FORWARD-} ]]; then
  exec uvx --python 3.13 --from tinybird@latest tb "$@"
else
  exec uvx --python 3.13 --from tinybird-cli@latest tb "$@"
fi

